local config = require 'one-hunter.config'

local colors = {
  standardWhite = '#E0E0E0',
  standardBlack = '#34393E',
}

if vim.o.background == 'light' then
  colors.editorBackground = '#ffffff'
  colors.sidebarBackground = '#f8f8f8'
  colors.popupBackground = '#ffffff'
  colors.floatingWindowBackground = '#ffffff'
  colors.menuOptionBackground = '#ffffff'

  colors.mainText = '#313131'
  colors.emphasisText = '#212121'
  colors.commandText = '#313131'
  colors.inactiveText = '#ADADAD'
  colors.disabledText = '#E6E6E6'
  colors.lineNumberText = '#ADADAD'
  colors.selectedText = '#424242'
  colors.inactiveSelectionText = '#ADADAD'

  colors.windowBorder = '#ADADAD'
  colors.focusedBorder = '#E1239A'
  colors.emphasizedBorder = '#ADADAD'

  colors.syntaxFunction = '#0488DB'
  colors.syntaxError = '#E61F44'
  colors.syntaxKeyword = '#E1239A'
  colors.errorText = '#E61F44'
  colors.warningText = '#FF7E00'
  colors.linkText = '#E1239A'
  colors.commentText = '#A8A8A8'
  colors.stringText = '#0BA463'
  colors.successText = '#0BA463'
  colors.warningEmphasis = '#FF7E00'
  colors.specialKeyword = '#B267E6'
  colors.syntaxOperator = '#5D5D5D'
  colors.foregroundEmphasis = '#000000'
  colors.terminalGray = '#ADADAD'

  colors.bg = '#ffffff'
  colors.bg_dark = '#eaeaea'
  colors.bg_darker = '#F4F4F4'
  colors.bg_light = '#f8f8f8'
  colors.bg_visual = '#E6E6E6'
  colors.bg_float = '#F4F4F4'

  colors.fg = '#313131'
  colors.fg_dim = '#31313188'
  colors.fg_bright = '#313131'

  -- Grays
  colors.gray = '#A8A8A8'
  colors.gray_dark = '#ADADAD'
  colors.gray_light = '#B3B3B3'
  colors.gray_border = '#ADADAD'

  -- Accent colors
  colors.cyan = '#0BA463'
  colors.cyan_bright = '#5BD1B9'
  colors.yellow = '#FF7E00'
  colors.blue = '#0488DB'
  colors.blue_light = '#0488DB'
  colors.blue_pale = '#689FDE'
  colors.blue_bright = '#2372E1'
  colors.pink = '#E1239A'
  colors.pink_bright = '#E1239A'
  colors.purple = '#B267E6'
  colors.purple_bright = '#D7C9F0'
  colors.red = '#E61F44'
  colors.red_dark = '#E34234'
  colors.green = '#0BA463'

  -- Terminal colors
  colors.terminalBlack = '#F4F4F4'
  colors.terminalRed = '#E61F44'
  colors.terminalGreen = '#0BA463'
  colors.terminalYellow = '#0488DB'
  colors.terminalBlue = '#0488DB'
  colors.terminalMagenta = '#E1239A'
  colors.terminalCyan = '#B267E6'
  colors.terminalWhite = '#313131'
  colors.terminalBrightBlack = '#ADADAD'
  colors.terminalBrightRed = '#E61F44'
  colors.terminalBrightGreen = '#5BD1B9'
  colors.terminalBrightYellow = '#0488DB'
  colors.terminalBrightBlue = '#0488DB'
  colors.terminalBrightMagenta = '#E1239A'
  colors.terminalBrightCyan = '#D7C9F0'
  colors.terminalBrightWhite = '#313131'

  -- Special
  colors.none = 'NONE'
else
  colors.editorBackground = '#191d21'
  colors.sidebarBackground = '#14181b'
  colors.popupBackground = '#34393E'
  colors.floatingWindowBackground = '#14181B'
  colors.menuOptionBackground = '#34393E'

  colors.mainText = '#e0e0e0'
  colors.emphasisText = '#fafafa'
  colors.commandText = '#e0e0e0'
  colors.inactiveText = '#484848'
  colors.disabledText = '#848484'
  colors.lineNumberText = '#727272'
  colors.selectedText = '#eaeaea'
  colors.inactiveSelectionText = '#f5f5f5'

  colors.windowBorder = '#45505b'
  colors.focusedBorder = '#F4457D'
  colors.emphasizedBorder = '#45505b'
  colors.syntaxError = '#F44747'
  colors.syntaxFunction = '#43AAF9'
  colors.warningText = '#F9C35A'
  colors.syntaxKeyword = '#F4457D'
  colors.linkText = '#F4457D'
  colors.stringText = '#5BD1B9'
  colors.warningEmphasis = '#F9C35A'
  colors.successText = '#5BD1B9'
  colors.errorText = '#E61F44'
  colors.specialKeyword = '#B267E6'
  colors.commentText = '#888888'
  colors.syntaxOperator = '#EFEFEF'
  colors.foregroundEmphasis = '#ffffff'
  colors.terminalGray = '#5c5c5c'

  colors.bg = '#191d21'
  colors.bg_dark = '#14181b'
  colors.bg_darker = '#101315'
  colors.bg_light = '#1d2226'
  colors.bg_visual = '#34393E'
  colors.bg_float = '#14181B'

  colors.fg = '#E0E0E0'
  colors.fg_dim = '#E0E0E088'
  colors.fg_bright = '#E6E6E6'

  -- Grays
  colors.gray = '#888888'
  colors.gray_dark = '#45505b'
  colors.gray_light = '#9CAAB4'
  colors.gray_border = '#45505b'

  -- Accent colors
  colors.cyan = '#5BD1B9'
  colors.cyan_bright = '#B7F0E5'
  colors.yellow = '#F9C35A'
  colors.blue = '#53A1FA'
  colors.blue_light = '#43AAF9'
  colors.blue_pale = '#9FBDE0'
  colors.blue_bright = '#A7C7ED'
  colors.pink = '#F4457D'
  colors.pink_bright = '#EE808B'
  colors.purple = '#B267E6'
  colors.purple_bright = '#D7C9F0'
  colors.red = '#E61F44'
  colors.red_dark = '#E34234'
  colors.green = '#A6E22E'

  -- Terminal colors
  colors.terminalBlack = '#34393E'
  colors.terminalRed = '#E61F44'
  colors.terminalGreen = '#5BD1B9'
  colors.terminalYellow = '#53A1FA'
  colors.terminalBlue = '#53A1FA'
  colors.terminalMagenta = '#F4457D'
  colors.terminalCyan = '#B267E6'
  colors.terminalWhite = '#E0E0E0'
  colors.terminalBrightBlack = '#45505b'
  colors.terminalBrightRed = '#E61F44'
  colors.terminalBrightGreen = '#B7F0E5'
  colors.terminalBrightYellow = '#A7C7ED'
  colors.terminalBrightBlue = '#A7C7ED'
  colors.terminalBrightMagenta = '#EE808B'
  colors.terminalBrightCyan = '#D7C9F0'
  colors.terminalBrightWhite = '#E0E0E0'

  -- Special
  colors.none = 'NONE'
end

return colors
